config:
  version: 'icehouse'
  pass: 'stack'
  vm_ssh_port: '4067'
  custom_repo: 'http://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-3.noarch.rpm'
  instack_undercloud_rpm: 'https://kojipkgs.fedoraproject.org//packages/instack-undercloud/0.0.16/1.fc21/noarch/instack-undercloud-0.0.16-1.fc21.noarch.rpm'
  updated_rpms_list:
      - 'https://kojipkgs.fedoraproject.org//packages/openstack-tripleo-heat-templates/0.4.4/3.fc21/noarch/openstack-tripleo-heat-templates-0.4.4-3.fc21.noarch.rpm'
      - 'https://kojipkgs.fedoraproject.org//packages/openstack-tripleo-image-elements/0.6.5/7.fc21/noarch/openstack-tripleo-image-elements-0.6.5-7.fc21.noarch.rpm'
      - 'https://kojipkgs.fedoraproject.org//packages/diskimage-builder/0.1.15/3.fc21/noarch/diskimage-builder-0.1.15-3.fc21.noarch.rpm'
  custom_instack_images: 'http://file.rdu.redhat.com/~jslagle/selinux-proposed-images/'

